# @format

📖frontend:
  - frontend/*
⚙backend:
  - backend/*
⚡infra:
  - docker-compose.yml
  - infra/*
✈ci:
  - .github/workflows/*
  - .github/labeler.yml
📄docs:
  - README.md
  - memo.md
  - LICENSE
# ⚙config:
# 🧪tests:
