#
# dc -f compose-prod.yml up -d --build
#
services:
  go:
    image: ghcr.io/usuyuki/musubineru_api:latest
    # build:
    #   context: ./backend
    #   dockerfile: ../infra/prod/go/Dockerfile
    # ports:
    #   - "8080:8080"
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    restart: always

networks:
  default:
    name: nginx-proxy
    external: true
