services:
  go:
    image: ghcr.io/usuyuki/musubineru_api:latest
    # build:
    #   context: .
    #   dockerfile: ./infra/prod/go/Dockerfile
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 8080:8080

networks:
  default:
    name: nginx-proxy
    external: true
