services:
  go:
    image: ghcr.io/usuyuki/musubineru_api:latest
    # build:
    #   context: .
    #   dockerfile: ./infra/prod/go/Dockerfile
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    restart: always

networks:
  default:
    name: nginx-proxy
    external: true
