name: API鯖への自動デプロイ

on:
  pull_request:
    branches:
      - main
    tags:
      - "⚙backend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USERNAME }}
          key: ${{ secrets.API_SSH_KEY }}
          port: ${{ secrets.API_PORT }}
          script: whoami

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: yarn install
        # ssh接続のための接続
        env:
          PRIVATE_KEY: ${{ secrets.API_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$API_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          yarn install

      - name: Run Pull
        run: |
          cd ${{ secrets.SERVER_DEPLOY_DIR }}
          git pull origin main
