name: API鯖への自動デプロイ

on:
  pull_request:
    branches:
      - main
    tags:
      - "⚙backend"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USERNAME }}
          key: ${{ secrets.API_SSH_KEY }}
          port: ${{ secrets.API_PORT }}
          script: whoami
