name: APIの自動デプロイ

on: [pull_request]
# on:
#   pull_request:
#     branches:
#       - main
#     types: [closed]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USUYUKI_GITHUB_TOKEN }}
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infra/prod/go/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/musubineru_api:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/musubineru_api:latest
          labels: latest

  deploy:
    name: Deploy to Server
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.MUSUBINERU_SERVER_PATH }}
            git checkout main
            git pull origin main
            # docker compose upしても正しく降ってこないので、一旦最新を明示的にpullさせる
            docker pull ghcr.io/usuyuki/musubineru_api:latest
            docker compose -f compose-prod.yml up -d --build
